import { beforeEach, describe, expect, it, vi } from 'vitest';

vi.mock('../lib/prisma', () => ({
  prisma: {
    transaction: {
      findMany: vi.fn(),
      count: vi.fn(),
      aggregate: vi.fn(),
      create: vi.fn(),
      findUnique: vi.fn(),
      update: vi.fn(),
      delete: vi.fn(),
    },
  },
}));

import { prisma } from '../lib/prisma';

function deferred<T>() {
  let resolve!: (value: T | PromiseLike<T>) => void;
  let reject!: (reason?: unknown) => void;
  const promise = new Promise<T>((res, rej) => {
    resolve = res;
    reject = rej;
  });
  return { promise, resolve, reject };
}

describe('Transaction Service', () => {
  beforeEach(() => {
    vi.clearAllMocks();
  });

  it('applies text search across description, category, and payee', async () => {
    vi.mocked(prisma.transaction.findMany).mockResolvedValue([]);
    vi.mocked(prisma.transaction.count).mockResolvedValue(0);

    const { listTransactions } = await import('../services/transaction.service');
    await listTransactions({ search: 'repair' });

    const findManyCall = vi.mocked(prisma.transaction.findMany).mock.calls[0][0];

    expect(findManyCall?.where?.OR).toEqual([
      { description: { contains: 'repair', mode: 'insensitive' } },
      { category: { contains: 'repair', mode: 'insensitive' } },
      { payee: { contains: 'repair', mode: 'insensitive' } },
    ]);
  });

  it('normalizes dateTo to include the full day', async () => {
    vi.mocked(prisma.transaction.findMany).mockResolvedValue([]);
    vi.mocked(prisma.transaction.count).mockResolvedValue(0);

    const { listTransactions } = await import('../services/transaction.service');
    await listTransactions({ dateTo: '2026-04-03' });

    const findManyCall = vi.mocked(prisma.transaction.findMany).mock.calls[0][0];
    expect(findManyCall?.where?.date).toMatchObject({
      lt: new Date('2026-04-04T00:00:00.000Z'),
    });
  });

  it('runs the paginated list query and count in parallel', async () => {
    const findManyDeferred = deferred<never[]>();
    const countDeferred = deferred<number>();

    vi.mocked(prisma.transaction.findMany).mockReturnValue(findManyDeferred.promise as never);
    vi.mocked(prisma.transaction.count).mockReturnValue(countDeferred.promise as never);

    const { listTransactions } = await import('../services/transaction.service');
    const pending = listTransactions({ page: 2, limit: 5 });

    expect(prisma.transaction.findMany).toHaveBeenCalledTimes(1);
    expect(prisma.transaction.count).toHaveBeenCalledTimes(1);

    findManyDeferred.resolve([]);
    countDeferred.resolve(0);
    await pending;
  });

  it('exports the full filtered result set as CSV without pagination', async () => {
    vi.mocked(prisma.transaction.findMany).mockResolvedValue([
      {
        id: 'txn-1',
        type: 'EXPENSE',
        amount: { toNumber: () => 125.5 },
        date: new Date('2026-04-02T00:00:00.000Z'),
        category: 'Materials',
        description: 'Fence panels',
        payee: 'ABC Supply',
        paymentMethod: 'CASH',
        projectId: null,
        project: null,
        sourceField: null,
        isAutoGenerated: false,
        createdAt: new Date('2026-04-02T12:00:00.000Z'),
        updatedAt: new Date('2026-04-02T12:00:00.000Z'),
      },
      {
        id: 'txn-2',
        type: 'INCOME',
        amount: { toNumber: () => 5000 },
        date: new Date('2026-04-03T00:00:00.000Z'),
        category: 'Install',
        description: 'Project payment',
        payee: 'John, Doe',
        paymentMethod: 'CHECK',
        projectId: 'project-1',
        project: { customer: 'John Doe' },
        sourceField: 'customerPaid',
        isAutoGenerated: true,
        createdAt: new Date('2026-04-03T12:00:00.000Z'),
        updatedAt: new Date('2026-04-03T12:00:00.000Z'),
      },
    ] as never);

    const { exportTransactions } = await import('../services/transaction.service');
    const csv = await exportTransactions({ category: 'Install', search: 'pay' });

    const findManyCall = vi.mocked(prisma.transaction.findMany).mock.calls[0][0];

    expect(findManyCall?.skip).toBeUndefined();
    expect(findManyCall?.take).toBeUndefined();
    expect(findManyCall?.where?.category).toEqual({
      contains: 'Install',
      mode: 'insensitive',
    });
    expect(findManyCall?.where?.OR).toEqual([
      { description: { contains: 'pay', mode: 'insensitive' } },
      { category: { contains: 'pay', mode: 'insensitive' } },
      { payee: { contains: 'pay', mode: 'insensitive' } },
    ]);
    expect(csv).toContain('id,type,amount,date,category,description,payee,paymentMethod,projectId,projectCustomer,sourceField,isAutoGenerated,createdAt,updatedAt');
    expect(csv).toContain('txn-1,EXPENSE,125.5,2026-04-02,Materials,Fence panels,ABC Supply,CASH,,,,false,2026-04-02T12:00:00.000Z,2026-04-02T12:00:00.000Z');
    expect(csv).toContain('"John, Doe"');
  });

  it('sets CSV headers on the export route', async () => {
    vi.resetModules();
    vi.doMock('../middleware/auth', () => ({
      requireAuth: (req: { user?: { userId: string } }, _res: unknown, next: () => void) => {
        req.user = { userId: 'user-1' };
        next();
      },
    }));
    vi.doMock('../middleware/validate', () => ({
      validate: () => (_req: unknown, _res: unknown, next: () => void) => next(),
      validateQuery: () => (_req: unknown, _res: unknown, next: () => void) => next(),
    }));
    vi.doMock('../services/transaction.service', async () => {
      const actual = await vi.importActual<typeof import('../services/transaction.service')>(
        '../services/transaction.service'
      );
      return {
        ...actual,
        exportTransactions: vi.fn().mockResolvedValue('id,type\n1,EXPENSE'),
      };
    });

    const { default: express } = await import('express');
    const { transactionRouter } = await import('../routes/transactions');
    const { exportTransactions } = await import('../services/transaction.service');

    void express;

    const layer = transactionRouter.stack.find(
      (entry: any) => entry.route?.path === '/export' && entry.route?.methods?.get
    );
    if (!layer?.route) {
      throw new Error('Export route not registered');
    }

    const req = { query: { search: 'repair' }, headers: {} } as never;
    const headers = new Map<string, string>();
    const res = {
      status: vi.fn().mockReturnThis(),
      json: vi.fn().mockReturnThis(),
      send: vi.fn().mockReturnThis(),
      setHeader: vi.fn((key: string, value: string) => {
        headers.set(key.toLowerCase(), value);
        return res;
      }),
    } as never;

    for (const stackEntry of layer.route.stack) {
      await new Promise<void>((resolve, reject) => {
        const maybePromise = stackEntry.handle(req, res, (err?: unknown) => {
          if (err) {
            reject(err);
            return;
          }
          resolve();
        });

        if (maybePromise && typeof (maybePromise as Promise<unknown>).then === 'function') {
          (maybePromise as Promise<unknown>).then(() => resolve(), reject);
        }
      });
    }

    expect(headers.get('content-type')).toContain('text/csv');
    expect(headers.get('content-disposition')).toContain('transactions.csv');
    expect((res as { send: ReturnType<typeof vi.fn> }).send).toHaveBeenCalledWith('id,type\n1,EXPENSE');
    expect(vi.mocked(exportTransactions)).toHaveBeenCalledWith(
      expect.objectContaining({ search: 'repair' })
    );
  });
});
