import { Prisma } from '@prisma/client';
import { prisma } from '../lib/prisma';
import {
  type CreateTransactionDTO,
  type UpdateTransactionDTO,
  type TransactionListQuery,
} from '@fencetastic/shared';
import { AppError } from '../middleware/error-handler';

// Helper: convert Prisma Decimal to number
function d(val: Prisma.Decimal | null | undefined): number {
  if (val == null) return 0;
  if (typeof (val as unknown as { toNumber?: () => number }).toNumber === 'function') {
    return (val as unknown as { toNumber: () => number }).toNumber();
  }
  return Number(val);
}

export async function listTransactions(query: TransactionListQuery = {}) {
  const {
    page = 1,
    limit = 20,
    type,
    category,
    projectId,
    dateFrom,
    dateTo,
  } = query;

  const where: Prisma.TransactionWhereInput = {};

  if (type) {
    where.type = type;
  }
  if (category) {
    where.category = { contains: category, mode: 'insensitive' };
  }
  if (projectId) {
    where.projectId = projectId;
  }
  if (dateFrom || dateTo) {
    where.date = {};
    if (dateFrom) {
      (where.date as Prisma.DateTimeFilter).gte = new Date(dateFrom);
    }
    if (dateTo) {
      (where.date as Prisma.DateTimeFilter).lte = new Date(dateTo);
    }
  }

  const [transactions, total] = await Promise.all([
    prisma.transaction.findMany({
      where,
      include: {
        project: {
          select: { customer: true },
        },
      },
      orderBy: { date: 'desc' },
      skip: (page - 1) * limit,
      take: limit,
    }),
    prisma.transaction.count({ where }),
  ]);

  const data = transactions.map((t) => ({
    id: t.id,
    type: t.type,
    amount: d(t.amount),
    date: t.date.toISOString().split('T')[0],
    category: t.category,
    description: t.description,
    payee: t.payee,
    paymentMethod: t.paymentMethod,
    projectId: t.projectId,
    projectCustomer: t.project?.customer ?? null,
    sourceField: t.sourceField,
    isAutoGenerated: t.isAutoGenerated,
    createdAt: t.createdAt.toISOString(),
    updatedAt: t.updatedAt.toISOString(),
  }));

  return {
    data,
    pagination: {
      page,
      limit,
      total,
      totalPages: Math.ceil(total / limit),
    },
  };
}

export async function getTransactionSummary(period: 'mtd' | 'ytd') {
  const now = new Date();
  let from: Date;

  if (period === 'mtd') {
    from = new Date(now.getFullYear(), now.getMonth(), 1);
  } else {
    from = new Date(now.getFullYear(), 0, 1);
  }

  const [incomeAgg, expenseAgg] = await Promise.all([
    prisma.transaction.aggregate({
      where: { type: 'INCOME', date: { gte: from } },
      _sum: { amount: true },
    }),
    prisma.transaction.aggregate({
      where: { type: 'EXPENSE', date: { gte: from } },
      _sum: { amount: true },
    }),
  ]);

  const totalIncome = d(incomeAgg._sum.amount);
  const totalExpenses = d(expenseAgg._sum.amount);

  return {
    totalIncome,
    totalExpenses,
    netProfit: Number((totalIncome - totalExpenses).toFixed(2)),
  };
}

export async function createTransaction(dto: CreateTransactionDTO) {
  const transaction = await prisma.transaction.create({
    data: {
      type: dto.type,
      amount: dto.amount,
      date: new Date(dto.date),
      category: dto.category,
      description: dto.description,
      payee: dto.payee ?? null,
      paymentMethod: dto.paymentMethod ?? null,
      projectId: dto.projectId ?? null,
      isAutoGenerated: false,
    },
  });

  return { id: transaction.id };
}

export async function updateTransaction(id: string, dto: UpdateTransactionDTO) {
  const existing = await prisma.transaction.findUnique({ where: { id } });
  if (!existing) {
    throw new AppError(404, 'Transaction not found', 'TRANSACTION_NOT_FOUND');
  }

  const updateData: Prisma.TransactionUpdateInput = {};

  if (dto.type !== undefined) updateData.type = dto.type;
  if (dto.amount !== undefined) updateData.amount = dto.amount;
  if (dto.date !== undefined) updateData.date = new Date(dto.date);
  if (dto.category !== undefined) updateData.category = dto.category;
  if (dto.description !== undefined) updateData.description = dto.description;
  if (dto.payee !== undefined) updateData.payee = dto.payee;
  if (dto.paymentMethod !== undefined) updateData.paymentMethod = dto.paymentMethod;
  if (dto.projectId !== undefined) {
    updateData.project = dto.projectId
      ? { connect: { id: dto.projectId } }
      : { disconnect: true };
  }

  const updated = await prisma.transaction.update({
    where: { id },
    data: updateData,
  });

  return { id: updated.id };
}

export async function deleteTransaction(id: string) {
  const existing = await prisma.transaction.findUnique({ where: { id } });
  if (!existing) {
    throw new AppError(404, 'Transaction not found', 'TRANSACTION_NOT_FOUND');
  }

  await prisma.transaction.delete({ where: { id } });
}

export async function createAutoTransaction(
  projectId: string,
  type: 'INCOME' | 'EXPENSE',
  category: string,
  sourceField: string,
  delta: number,
  payee: string
) {
  if (delta === 0) return;

  await prisma.transaction.create({
    data: {
      type,
      amount: Math.abs(delta),
      date: new Date(),
      category,
      description: `Auto: ${sourceField} updated (delta: ${delta > 0 ? '+' : ''}${delta})`,
      payee,
      projectId,
      sourceField,
      isAutoGenerated: true,
    },
  });
}

export async function getMonthlyBreakdown() {
  const rows = await prisma.$queryRaw<
    Array<{ month: string; type: string; total: string }>
  >`
    SELECT
      TO_CHAR("date", 'YYYY-MM') AS month,
      type,
      SUM(amount)::text AS total
    FROM transactions
    GROUP BY month, type
    ORDER BY month ASC
  `;

  // Pivot into { month, income, expenses }
  const map = new Map<string, { month: string; income: number; expenses: number }>();
  for (const row of rows) {
    if (!map.has(row.month)) {
      map.set(row.month, { month: row.month, income: 0, expenses: 0 });
    }
    const entry = map.get(row.month)!;
    if (row.type === 'INCOME') {
      entry.income = Number(row.total);
    } else {
      entry.expenses = Number(row.total);
    }
  }

  return Array.from(map.values());
}

export async function getCategoryBreakdown() {
  const rows = await prisma.$queryRaw<
    Array<{ category: string; total: string }>
  >`
    SELECT category, SUM(amount)::text AS total
    FROM transactions
    WHERE type = 'EXPENSE'
    GROUP BY category
    ORDER BY total DESC
  `;

  return rows.map((r) => ({
    category: r.category,
    total: Number(r.total),
  }));
}
