import { act, useState, type ReactNode } from 'react';
import { createRoot, type Root } from 'react-dom/client';
import { MemoryRouter } from 'react-router-dom';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import PageShell, { PageShellProvider, type PageShellConfig } from '@/components/layout/page-shell';
import FinancesPage from './finances';

const useTransactionsMock = vi.fn();
const useTransactionSummaryMock = vi.fn();
const useMonthlyBreakdownMock = vi.fn();
const useCategoryBreakdownMock = vi.fn();
const exportTransactionsMock = vi.fn();

vi.mock('@/hooks/use-transactions', () => ({
  useTransactions: (...args: unknown[]) => useTransactionsMock(...args),
  useTransactionSummary: (...args: unknown[]) => useTransactionSummaryMock(...args),
  useMonthlyBreakdown: (...args: unknown[]) => useMonthlyBreakdownMock(...args),
  useCategoryBreakdown: (...args: unknown[]) => useCategoryBreakdownMock(...args),
}));

vi.mock('@/components/finances/redesign/finances-summary-strip', () => ({
  FinancesSummaryStrip: ({ period }: { period: string }) => <div data-testid="summary-strip">{period}</div>,
}));

vi.mock('@/components/finances/redesign/finances-overview-panels', () => ({
  FinancesOverviewPanels: () => <div data-testid="overview-panels" />,
}));

vi.mock('@/components/finances/redesign/finances-transaction-table', () => ({
  FinancesTransactionTable: ({ query }: { query: { search?: string } }) => (
    <div data-testid="transaction-table">{query.search ?? 'none'}</div>
  ),
}));

vi.mock('@/components/finances/redesign/transactions-export', () => ({
  exportTransactions: (...args: unknown[]) => exportTransactionsMock(...args),
  buildTransactionsExportParams: vi.fn(),
}));

vi.mock('@/lib/api', () => ({
  api: {
    post: vi.fn(),
  },
}));

function makeTransaction(overrides: Partial<Record<string, unknown>> = {}) {
  return {
    id: 'tx-1',
    type: 'EXPENSE',
    amount: 402.74,
    date: '2026-04-01',
    category: 'Materials',
    description: 'Lumber supply',
    payee: 'Vendor',
    paymentMethod: null,
    projectId: null,
    sourceField: null,
    isAutoGenerated: false,
    createdAt: '2026-04-01T00:00:00.000Z',
    updatedAt: '2026-04-01T00:00:00.000Z',
    ...overrides,
  };
}

function ShellHarness({ children }: { children: ReactNode }) {
  const [shellConfig, setShellConfig] = useState<PageShellConfig>({});

  return (
    <PageShellProvider value={setShellConfig}>
      <PageShell
        onOpenSidebar={vi.fn()}
        {...shellConfig}
      >
        {children}
      </PageShell>
    </PageShellProvider>
  );
}

describe('FinancesPage', () => {
  let container: HTMLDivElement;
  let root: Root;

  beforeEach(() => {
    container = document.createElement('div');
    document.body.appendChild(container);
    root = createRoot(container);
    useTransactionsMock.mockReset();
    useTransactionSummaryMock.mockReset();
    useMonthlyBreakdownMock.mockReset();
    useCategoryBreakdownMock.mockReset();
    exportTransactionsMock.mockReset();
    vi.spyOn(HTMLAnchorElement.prototype, 'click').mockImplementation(() => {});
    Object.defineProperty(URL, 'createObjectURL', {
      configurable: true,
      value: vi.fn(() => 'blob:mock'),
    });
    Object.defineProperty(URL, 'revokeObjectURL', {
      configurable: true,
      value: vi.fn(),
    });
  });

  afterEach(() => {
    act(() => {
      root.unmount();
    });
    container.remove();
  });

  it('updates the live query, switches summary period, and exports with the current filters', () => {
    useTransactionsMock.mockReturnValue({
      data: [makeTransaction()],
      pagination: { page: 1, limit: 20, total: 1, totalPages: 1 },
      isLoading: false,
      error: null,
      refetch: vi.fn(),
    });
    useTransactionSummaryMock.mockReturnValue({
      summary: { totalIncome: 124500, totalExpenses: 42320, netProfit: 82180 },
      isLoading: false,
    });
    useMonthlyBreakdownMock.mockReturnValue({
      data: [
        { month: 'Jan', income: 12000, expenses: 4000 },
        { month: 'Feb', income: 18000, expenses: 6000 },
      ],
      isLoading: false,
    });
    useCategoryBreakdownMock.mockReturnValue({
      data: [
        { category: 'Materials', total: 22000 },
        { category: 'Labor', total: 12000 },
      ],
      isLoading: false,
    });
    exportTransactionsMock.mockResolvedValue(new Blob(['csv']));

    act(() => {
      root.render(
        <MemoryRouter future={{ v7_startTransition: true, v7_relativeSplatPath: true }}>
          <ShellHarness>
            <FinancesPage />
          </ShellHarness>
        </MemoryRouter>
      );
    });

    expect(container.textContent).toContain('Finances');
    expect(container.textContent).toContain('Add Transaction');
    expect(container.textContent).toContain('Export');
    expect(container.querySelector('[data-testid="summary-strip"]')?.textContent).toBe('mtd');

    const searchInput = container.querySelector('input[placeholder="Search description, category, or payee..."]');
    expect(searchInput).not.toBeNull();

    act(() => {
      if (searchInput) {
        (searchInput as HTMLInputElement).value = 'oak';
        searchInput.dispatchEvent(
          new Event('input', {
            bubbles: true,
            cancelable: true,
          })
        );
        searchInput.dispatchEvent(
          new Event('change', {
            bubbles: true,
            cancelable: true,
          })
        );
      }
    });

    const ytdButton = Array.from(container.querySelectorAll('button')).find((button) => button.textContent?.includes('YTD'));
    expect(ytdButton).not.toBeUndefined();

    act(() => {
      ytdButton?.dispatchEvent(
        new MouseEvent('click', {
          bubbles: true,
          cancelable: true,
          button: 0,
        })
      );
    });

    expect(useTransactionSummaryMock.mock.calls.at(-1)?.[0]).toBe('ytd');

    const exportButton = Array.from(container.querySelectorAll('button')).find((button) =>
      button.textContent?.includes('Export')
    );
    expect(exportButton).not.toBeUndefined();

    act(() => {
      exportButton?.dispatchEvent(
        new MouseEvent('click', {
          bubbles: true,
          cancelable: true,
          button: 0,
        })
      );
    });

    expect(exportTransactionsMock).toHaveBeenCalledWith(expect.objectContaining({ page: 1, limit: 20 }));
  });
});
